export const testsByCondition: { [key: string]: string[] } = {
    "Nadciśnienie tętnicze": [
      "Pomiar ciśnienia (domowy, Holter RR)",
      "Elektrolity (Na, K)",
      "Kreatynina",
      "EKG",
      "Morfologia z rozmazem ręcznym",
    ],
    "Miażdżyca": [
      "Morfologia",
      "Lipidogram",
      "Homocysteina",
      "CRP",
      "USG Doppler tętnic",
    ],
    "Choroba niedokrwienna serca": [
      "EKG",
      "Troponiny",
      "Echokardiografia",
      "Próba wysiłkowa",
      "Morfologia",
    ],
    "Hiperlipidemia": [
      "Lipidogram (cholesterol całkowity, HDL, LDL, trójglicerydy)",
      "Morfologia",
    ],
    "Choroby wątroby": [
      "Próby wątrobowe",
      "USG jamy brzusznej",
      "Morfologia",
    ],
    "Choroby trzustki": [
      "Amylaza",
      "Lipaza",
      "Morfologia",
    ],
    "Kamica żółciowa": [
      "USG jamy brzusznej",
      "Morfologia",
      "Badania wątroby",
    ],
    "Zespół jelita drażliwego (IBS)": [
      "CRP",
      "Kalprotektyna w kale",
      "Testy na nietolerancje",
      "Morfologia",
    ],
    "Choroba uchyłkowa jelit": [
      "Kolonoskopia",
      "TK jamy brzusznej",
      "Morfologia",
    ],
    "Zaparcia przewlekłe": [
      "Morfologia",
      "Elektrolity",
      "TSH, FT3, FT4",
      "Badanie kału (pasożyty, krew utajona)",
      "Kalprotektyna",
    ],
    "Biegunki przewlekłe": [
      "Morfologia",
      "Elektrolity",
      "TSH, FT3, FT4",
      "Badanie kału (pasożyty, krew utajona)",
      "Kalprotektyna",
    ],
    "Nietolerancje pokarmowe": [
      "Test wodorowy (laktoza, fruktoza)",
      "Morfologia",
    ],
    "Zapalenie żołądka": [
      "Gastroskopia",
      "Test na Helicobacter pylori",
      "Morfologia",
    ],
    "Celiakia": [
      "Przeciwciała: anty-tTG, EMA, DGP",
      "Gastroskopia z biopsją",
      "Morfologia",
    ],
    "Rak jelita grubego": [
      "Kolonoskopia",
      "Krew utajona w kale",
      "CEA",
    ],
    "Rak żołądka": [
      "Gastroskopia",
      "CA 72-4",
    ],
    "Rak przełyku": [
      "Gastroskopia",
    ],
    "Rak trzustki": [
      "CA 19-9",
      "USG/TK/MR",
    ],
    "Rak wątroby": [
      "AFP",
      "USG/TK",
    ],
    "Rak piersi": [
      "USG",
      "Mammografia",
      "Biopsja",
      "CA 15-3",
    ],
    "Rak prostaty": [
      "PSA",
      "USG",
      "Biopsja",
    ],
    "Rak jajnika": [
      "CA-125",
      "USG",
    ],
    "Osteoporoza": [
      "Densytometria (DXA)",
      "Wapń",
      "Fosfor",
      "Witamina D3",
      "Morfologia",
    ],
    "Osteopenia": [
      "Densytometria (DXA)",
      "Wapń",
      "Fosfor",
      "Witamina D3",
      "Morfologia",
    ],
    "Choroba zwyrodnieniowa stawów": [
      "RTG stawów",
      "CRP",
      "OB.",
      "Morfologia",
    ],
    "Dna moczanowa": [
      "Kwas moczowy",
      "Kreatynina",
      "Morfologia",
    ],
    "Cukrzyca typu 2": [
      "Glukoza",
      "Insulina",
      "Morfologia",
    ],
    "Cukrzyca typu 1": [
      "Glukoza",
      "Morfologia",
    ],
    "Zaburzenia lipidowe": [
      "Lipidogram",
      "Morfologia",
    ],
    "Zaburzenia pracy tarczycy: niedoczynność, nadczynność": [
      "TSH",
      "FT3",
      "FT4",
      "Anty-TPO",
      "Anty-TG",
      "USG tarczycy",
      "Morfologia",
    ],
    "Kamica nerkowa": [
      "USG nerek",
      "Badanie ogólne moczu",
      "Kwas moczowy",
      "Wapń",
      "Fosfor",
      "Morfologia",
    ],
    "Przewlekła choroba nerek (PChN)": [
      "Kreatynina",
      "eGFR",
      "Mocznik",
      "Badanie moczu",
      "USG nerek",
      "Morfologia",
    ],
    "Choroby psychiczne i neurologiczne": [
      "Morfologia",
      "Witaminy z grupy B",
      "Witamina D3",
    ],
    "Choroby skóry": [
      "Morfologia",
      "CRP",
      "IgE (alergie)",
      "Witamina D3",
    ],
    "Anemia niedoborowa": [
      "Morfologia",
      "Ferrytyna",
      "Żelazo",
      "Witamina B12",
      "Kwas foliowy",
    ],
    "Krzywica": [
      "Wapń",
      "Fosfor",
      "Witamina D3",
      "PTH",
      "Morfologia",
    ],
    "Szkorbut": [
      "Witamina C",
      "Morfologia",
    ],
    "Awitaminozy": [
      "Witaminy (D, B12)",
      "Morfologia",
    ],
    "Zespół niedożywienia": [
      "Albumina",
      "Prealbumina",
      "Elektrolity",
      "Morfologia",
    ],
    "Alergie pokarmowe": [
      "Testy skórne",
      "Morfologia z rozmazem ręcznym",
    ],
    "Anoreksja": [
      "Elektrolity",
      "Morfologia",
      "Panel wątrobowy",
      "Kreatynina",
      "GFR",
      "EKG",
    ],
    "Bulimia": [
      "Elektrolity",
      "Morfologia",
      "Panel wątrobowy",
      "Kreatynina",
      "GFR",
      "EKG",
    ],
    "Zespół kompulsywnego objadania się": [
      "Elektrolity",
      "Morfologia",
      "Panel wątrobowy",
      "Kreatynina",
      "GFR",
      "EKG",
    ],
    "Choroby pasożytnicze (parazytozy)": [
      "Badanie kału (3-krotne)",
      "Morfologia z rozmazem ręcznym",
    ]
  };
  
