export const diseaseGroups: { [key: string]: string[] } = {
    "Choroby metaboliczne": [
      "Otyłość",
      "Cukrzyca typu 2",
      "Cukrzyca typu 1",
      "Insulinooporność",
      "Zespół metaboliczny",
      "Dna moczanowa (hiperurykemia)",
      "Niealkoholowe stłuszczenie wątroby (NAFLD)",
      "Przewlekła niewydolność wątroby",
      "Stłuszczenie wątroby",
    ],
    "Choroby układu krążenia": [
      "Nadciśnienie tętnicze",
      "Miażdżyca",
      "Choroba niedokrwienna serca",
      "Zawał mięśnia sercowego",
      "Udary mózgu (niedokrwienne)",
      "Niewydolność serca",
      "Hiperlipidemia",
    ],
    "Choroby przewodu pokarmowego": [
      "Choroba refluksowa przełyku (GERD)",
      "Choroby wątroby",
      "Choroby trzustki",
      "Choroby pęcherzyka żółciowego (kamica żółciowa)",
      "Zespół jelita drażliwego (IBS)",
      "Choroba uchyłkowa jelit",
      "Zaparcia przewlekłe",
      "Biegunki przewlekłe",
      "Nietolerancje pokarmowe",
      "Zapalenie żołądka",
      "Celiakia",
    ],
    "Choroby nowotworowe": [
      "Rak jelita grubego",
      "Rak żołądka",
      "Rak przełyku",
      "Rak trzustki",
      "Rak wątroby",
      "Rak piersi",
      "Rak prostaty",
      "Rak jajnika",
    ],
    "Choroby układu kostno-stawowego": [
      "Osteoporoza",
      "Osteopenia",
      "Choroba zwyrodnieniowa stawów",
      "Dna moczanowa",
    ],
    "Choroby endokrynologiczne": [
      "Cukrzyca typu 2",
      "Cukrzyca typu 1",
      "Zaburzenia lipidowe",
      "Zaburzenia pracy tarczycy: niedoczynność, nadczynność",
      "Choroby nerek",
      "Kamica nerkowa",
      "Przewlekła choroba nerek (PChN)",
      "Hiperurykemia i dna moczanowa",
      "PCOS",
    ],
    "Choroby psychiczne, neurologiczne i skórne": [
      "Depresja",
      "Zaburzenia lękowe",
      "Demencja",
      "Migreny",
      "Łuszczyca (nasilenie przy złej diecie)",
      "Atopowe zapalenie skóry (AZS)",
      "Trądzik",
      "Egzema",
    ],
    "Niedobory i nadmiary żywieniowe oraz zaburzenia odżywiania": [
      "Anemia niedoborowa",
      "Krzywica",
      "Szkorbut",
      "Awitaminozy",
      "Zespół niedożywienia",
      "Alergie pokarmowe",
      "Anoreksja",
      "Bulimia",
      "Zespół kompulsywnego objadania się",
    ],
    "Choroby pasożytnicze (parazytozy)": []
  };
  
